/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        roboto: ['Roboto', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        stick: ['"Stick No Bills"', 'sans-serif']
      },
      backgroundImage: {
        'primary-bg': "url('/src/assets/images/landingprimary.svg')",
        'secondary-bg': "url('/src/assets/images/landingsecondary.svg')",
        'img-bg': "url('/src/assets/images/bgimage.svg')"
      },
      colors: {
        primary: 'rgb(var(--primary) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        onboard_primary:'#1452D4',
        onboard_secondary:'#8B24E2',
        grey: '#3A3A3A',
        primarybg: '#FFFFFF4D',
        secondarybg: '#F7EDFF',
        textgrey: '#848586',
        bordergrey: '#DBDBDB',
        primarybglight: '#0062D224',
        greylight: '#3A3A3A24',
        bordergreylight: '#D4D4D4',
        textblack: '#000000',
        secondary_light: '#8B24E21F',
        pricing_text: '#808080',
        textwhite: '#FFFFFF',
        tableborder: '#D9D9D9',
        progress_yellow: '#FFCD0FFC',
        progress_blue: '#55EFC2',
        progress_green: '#B0F6B5',
        filter_border: '#8F8F8F',
        green_text: '#34C759',
        green_bg: '#DEF4E6',
        red_text: '#EB4824',
        red_bg: '#EA292914',
        search_bg: '#FFFFFF1A',
        switch_bg: '#D3D6E4',
        tab_bg: '#7676801F',
        primary_light: '#4581FF',
        grey_text: '#4A4747',
        delete_red: '#AD3F2B',
        day_select_bg: '#EEF3FF',
        day_select: '#CDDDFF',
        plan_bg_grey: '#E8ECFF',
        plan_grey: '#7287FD',
        plan_bg_green: '#F2FFCC',
        plan_green: '#8EB41C',
        plan_bg_blue: '#E1F2F6',
        plan_blue: '#4EABC3',
        plan_bg_purple: '#7E02F61F',
        plan_purple: '#8B24E2',
        badge_blue: '#00AFB5',
        badge_blue_bg: '#E6FFFD',
        badge_yellow: '#DDAF00FC',
        badge_yellow_bg: '#F9F0D0FC',
        badge_bg_green: '#CCFFCC',
        tabelsubtitle: '#504E4E',
        barchartexpense: '#8A00FF',
        revenue_other: '#A3AED0',
        memberprogress_light: '#4581FF45',
        inventory_light: '#FFCD0F45',
        purchase: '#EB4925',
        purchase_light: '#EB492545',
        progress_light_green: '#34C75945',
        Network: '#FF8548',
        Network_light: '#FF854845',
        payroll_light: '#8A00FF45',
        overview_bg: '#1452D4',
        payroll_bg: '#7DC20D',
        inventory_bg: '#FF9E97',
        taxes_bg: '#E33E10',
        general_bg: '#55EFC245',
        profile_blue: '#B6EECB',
        profile_green: '#A9E88B',
        profile_brown: '#DAE1A0',
        profile_pink: '#FFC8C4',
        profile_bg_blue: '#DAF6E4',
        profile_bg_green: '#D3F3C4',
        profile_bg_brown: '#ECF0CE',
        profile_bg_pink: '#FFE3E1',
        blue:'#407BFF',
        yellow:'#FFCD0F'
      }
    }
  },
  plugins: [require('tailwindcss-animate')]
}
