"""Add action_type in membermemberships

Revision ID: 584ade48400c
Revises: da1b7bd76f00
Create Date: 2026-03-23 05:52:17.750538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584ade48400c'
down_revision = 'da1b7bd76f00'
branch_labels = None
depends_on = None

# Enum definition for upgrade/downgrade
membership_action_type_enum = sa.Enum(
    'created', 'renewal', 'plan_change',
    name='membershipactiontypeenum'
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the enum type in the DB
    membership_action_type_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add the column to the table
    op.add_column(
        'member_memberships',
        sa.Column(
            'action_type',
            membership_action_type_enum,
            nullable=False,
            server_default='created'
        ),
        schema='membership'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_memberships', 'action_type', schema='membership')
    membership_action_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###