"""initial schema

Revision ID: e533a354d52f
Revises: 
Create Date: 2026-01-22 10:31:21.837852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e533a354d52f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'centeradmin', 'member', 'employee', name='user_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_users_email'), 'users', ['email'], unique=True, schema='shared')
    op.create_index(op.f('ix_shared_users_role'), 'users', ['role'], unique=False, schema='shared')
    op.create_index(op.f('ix_shared_users_status'), 'users', ['status'], unique=False, schema='shared')
    op.create_table('platform_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_table('address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.Enum('home', 'office', 'other', name='addresstype'), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=True),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='settings'
    )
    op.create_table('center_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['settings.center_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='settings'
    )
    op.create_table('designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('is_managerial', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='settings'
    )
    op.create_table('sku_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='settings'
    )
    op.create_table('tax_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_type', sa.Enum('gst', 'cgst_sgst', 'igst', 'vat', 'none', name='taxtype'), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_scope', sa.Enum('center_subscription', 'membership', 'networking', 'product', 'service', 'platform_fee', name='taxscope'), nullable=False, comment='Where this tax applies: subscription, membership, networking'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='settings'
    )
    op.create_index(op.f('ix_settings_tax_categories_tax_scope'), 'tax_categories', ['tax_scope'], unique=False, schema='settings')
    op.create_table('centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_name', sa.String(), nullable=False),
    sa.Column('center_category_id', sa.UUID(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=True),
    sa.Column('center_status', sa.Enum('active', 'inactive', 'suspended', 'closed', name='centerstatus'), nullable=False),
    sa.Column('network_enabled', sa.Boolean(), nullable=True),
    sa.Column('network_joined_date', sa.DateTime(), nullable=True),
    sa.Column('white_label_enabled', sa.Boolean(), nullable=True),
    sa.Column('kind_of_center', sa.JSON(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('trainer_count', sa.Integer(), nullable=True),
    sa.Column('currently_using_digital_tool', sa.String(), nullable=True),
    sa.Column('marketing_platform', sa.JSON(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('center_email', sa.String(), nullable=True),
    sa.Column('center_phone', sa.String(), nullable=True),
    sa.Column('live_class_enable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['settings.address.id'], ),
    sa.ForeignKeyConstraint(['center_category_id'], ['settings.center_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='center'
    )
    op.create_index(op.f('ix_center_centers_approval_status'), 'centers', ['approval_status'], unique=False, schema='center')
    op.create_index(op.f('ix_center_centers_center_name'), 'centers', ['center_name'], unique=False, schema='center')
    op.create_index(op.f('ix_center_centers_center_status'), 'centers', ['center_status'], unique=False, schema='center')
    op.create_table('sku',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['sku_category_id'], ['settings.sku_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code'),
    schema='shared'
    )
    op.create_table('center_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('network_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('white_label_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['settings.address.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['center.centers.id'], ),
    sa.ForeignKeyConstraint(['id'], ['shared.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('payment_orders',
    sa.Column('payment_order_id', sa.UUID(), nullable=False),
    sa.Column('payer_user_id', sa.UUID(), nullable=False),
    sa.Column('payer_type', sa.Enum('user', 'center_admin', 'system', name='payertype'), nullable=False),
    sa.Column('payee_type', sa.Enum('platform', 'center', 'trainer', name='payeetype'), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=True),
    sa.Column('order_type', sa.Enum('center_subscription', 'feature_purchase', 'renewal', 'upgrade', 'add_on', 'refund', name='ordertype'), nullable=False),
    sa.Column('reference_schema', sa.Enum('center', 'center_feature', 'wallet', 'invoice', name='referenceschema'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'created', 'processing', 'paid', 'failed', 'cancelled', 'refunded', 'expired', name='paymentorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['center.centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('payment_order_id'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_payment_orders_center_id'), 'payment_orders', ['center_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_payment_orders_order_type'), 'payment_orders', ['order_type'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_payment_orders_payer_user_id'), 'payment_orders', ['payer_user_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_payment_orders_status'), 'payment_orders', ['status'], unique=False, schema='billing')
    op.create_table('center_feature_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('payment_order_id', sa.UUID(), nullable=False),
    sa.Column('pricing_type', sa.Enum('monthly', 'yearly', 'one_time', name='pricingtype'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_category_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['center.centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['platform.platform_features.id'], ),
    sa.ForeignKeyConstraint(['payment_order_id'], ['billing.payment_orders.payment_order_id'], ),
    sa.ForeignKeyConstraint(['tax_category_id'], ['settings.tax_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='center'
    )
    op.create_index(op.f('ix_center_center_feature_subscriptions_center_id'), 'center_feature_subscriptions', ['center_id'], unique=False, schema='center')
    op.create_index(op.f('ix_center_center_feature_subscriptions_feature_id'), 'center_feature_subscriptions', ['feature_id'], unique=False, schema='center')
    op.create_index(op.f('ix_center_center_feature_subscriptions_payment_order_id'), 'center_feature_subscriptions', ['payment_order_id'], unique=False, schema='center')
    op.create_index(op.f('ix_center_center_feature_subscriptions_status'), 'center_feature_subscriptions', ['status'], unique=False, schema='center')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_center_feature_subscriptions_status'), table_name='center_feature_subscriptions', schema='center')
    op.drop_index(op.f('ix_center_center_feature_subscriptions_payment_order_id'), table_name='center_feature_subscriptions', schema='center')
    op.drop_index(op.f('ix_center_center_feature_subscriptions_feature_id'), table_name='center_feature_subscriptions', schema='center')
    op.drop_index(op.f('ix_center_center_feature_subscriptions_center_id'), table_name='center_feature_subscriptions', schema='center')
    op.drop_table('center_feature_subscriptions', schema='center')
    op.drop_index(op.f('ix_billing_payment_orders_status'), table_name='payment_orders', schema='billing')
    op.drop_index(op.f('ix_billing_payment_orders_payer_user_id'), table_name='payment_orders', schema='billing')
    op.drop_index(op.f('ix_billing_payment_orders_order_type'), table_name='payment_orders', schema='billing')
    op.drop_index(op.f('ix_billing_payment_orders_center_id'), table_name='payment_orders', schema='billing')
    op.drop_table('payment_orders', schema='billing')
    op.drop_table('center_admins', schema='auth')
    op.drop_table('sku', schema='shared')
    op.drop_index(op.f('ix_center_centers_center_status'), table_name='centers', schema='center')
    op.drop_index(op.f('ix_center_centers_center_name'), table_name='centers', schema='center')
    op.drop_index(op.f('ix_center_centers_approval_status'), table_name='centers', schema='center')
    op.drop_table('centers', schema='center')
    op.drop_index(op.f('ix_settings_tax_categories_tax_scope'), table_name='tax_categories', schema='settings')
    op.drop_table('tax_categories', schema='settings')
    op.drop_table('sku_categories', schema='settings')
    op.drop_table('designations', schema='settings')
    op.drop_table('center_categories', schema='settings')
    op.drop_table('address', schema='settings')
    op.drop_table('platform_features', schema='platform')
    op.drop_index(op.f('ix_shared_users_status'), table_name='users', schema='shared')
    op.drop_index(op.f('ix_shared_users_role'), table_name='users', schema='shared')
    op.drop_index(op.f('ix_shared_users_email'), table_name='users', schema='shared')
    op.drop_table('users', schema='shared')
    # ### end Alembic commands ###
